services:
  postgres:
    image: postgres:15-alpine
    container_name: sd-tasks-postgres
    environment:
      POSTGRES_DB: sd_tasks_db
      POSTGRES_USER: sd_tasks_user
      POSTGRES_PASSWORD: sd_tasks_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sd-tasks-network
    restart: unless-stopped

  backend:
    build: 
      context: .
      target: production
    container_name: sd-tasks-backend
    environment:
      NODE_ENV: production
      PORT: 3000
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      DATABASE_URL: postgresql://sd_tasks_user:sd_tasks_password@postgres:5432/sd_tasks_db
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - sd-tasks-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  sd-tasks-network:
    driver: bridge 