services:
  - type: web
    name: sd-tasks-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_NAME
        fromDatabase:
          name: sd-tasks-postgres
          property: database
      - key: DB_USER
        fromDatabase:
          name: sd-tasks-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sd-tasks-postgres
          property: password
      - key: DB_HOST
        fromDatabase:
          name: sd-tasks-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sd-tasks-postgres
          property: port

databases:
  - name: sd-tasks-postgres
    databaseName: sd_tasks_db
    user: sd_tasks_user
    plan: free